import type { Metadata } from "next";
import { Titillium_Web } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const titilliumweb = Titillium_Web({ subsets: ["latin"], weight: ['300'] });

export const metadata: Metadata = {
  title: "Find Meaning of Size Words",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={titilliumweb.className}>
        <Navbar/>
        {children}</body>
    </html>
  );
}
